services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    ports:
      - "5454:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - account-networks

  account:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - account-networks

networks:
  account-networks:
    driver: bridge

volumes:
  pg-data: